import { Injectable } from '@angular/core';
import { MenuItem } from '../../shared/misc/menu-item';

@Injectable({
  providedIn: 'root',
})
export class RestaurantMenu {
  readonly img = '../../images';
  menu: MenuItem[] = [
    {
      name: 'Fettuccine Alfredo',
      picture: 'images/fettuccine-alfredo.jpg',
      description: 'Fettuccine noodles sautéed with chicken, broccoli, and a creamy garlic sauce.',
      price: 16.99,
      category: 'Entree',
      allergens: ['Gluten', 'Dairy'],
      modifiers: ['No Chicken', 'No Broccoli'],
      note: '',
    },
    {
      name: 'Sirloin',
      picture: 'images/sirloin.jpg',
      description: 'A well-seasoned 6 oz. sirloin cooked to order.',
      price: 26.99,
      category: 'Entree',
      allergens: [],
      modifiers: ['Rare', 'Medium-Rare', 'Medium', 'Medium-Well', 'Well Done'],
      note: 'If you do not select an option, we will cook your steak medium. If multiple options are selected, we will use the most well-done selection.',
    },
    {
      name: 'Caesar Salad',
      picture: 'images/caesar-salad.jpg',
      description:
        'Crisp romaine lettuce tossed with Caesar dressing, croutons, and Parmesan cheese.',
      price: 10.99,
      category: 'Appetizer',
      allergens: ['Dairy', 'Gluten'],
      modifiers: ['No Croutons', 'No Cheese'],
      note: '',
    },
    {
      name: 'Breadsticks',
      picture: 'images/breadsticks.jpg',
      description: 'Soft, buttery breadsticks served with marinara sauce for dipping.',
      price: 5.99,
      category: 'Appetizer',
      allergens: ['Gluten', 'Dairy'],
      modifiers: [],
      note: '',
    },
    {
      name: 'Cheesy Ravioli',
      picture: 'images/cheesy-ravioli.jpg',
      description: 'Soft ravioli stuffed with a blend of cheeses, served with marinara sauce.',
      price: 14.99,
      category: 'Entree',
      allergens: ['Dairy', 'Gluten'],
      modifiers: [],
      note: '',
    },
    {
      name: 'Tiramisu',
      picture: 'images/tiramisu.jpg',
      description:
        'Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.',
      price: 7.99,
      category: 'Dessert',
      allergens: ['Dairy', 'Gluten', 'Eggs'],
      modifiers: [],
      note: '',
    },
    {
      name: 'Chocolate Cake',
      picture: 'images/chocolate-cake.jpg',
      description: 'Rich and moist chocolate cake topped with a creamy chocolate ganache.',
      price: 6.99,
      category: 'Dessert',
      allergens: ['Dairy', 'Gluten', 'Eggs'],
      modifiers: [],
      note: '',
    },
    {
      name: 'Gelato',
      picture: 'images/gelato.jpg',
      description: 'Creamy Italian-style ice cream.',
      price: 4.99,
      category: 'Dessert',
      allergens: ['Dairy'],
      modifiers: [],
      note: '',
    },
    {
      name: 'Lasagna',
      picture: 'images/lasagne.jpg',
      description:
        'Layers of pasta, meat sauce, ricotta, and mozzarella cheese baked to perfection.',
      price: 15.99,
      category: 'Entree',
      allergens: ['Dairy', 'Gluten'],
      modifiers: [],
      note: '',
    },
    {
      name: 'Margherita Pizza',
      picture: 'images/margherita-pizza.jpg',
      description:
        'Classic pizza with tomato sauce, fresh mozzarella, basil, and a drizzle of olive oil.',
      price: 13.99,
      category: 'Entree',
      allergens: ['Dairy', 'Gluten'],
      modifiers: [],
      note: '',
    },
    {
      name: 'Waffle Fries',
      picture: 'images/seasoned-waffle-fries.jpg',
      description: 'Crispy waffle-cut fries seasoned with a blend of herbs and spices.',
      price: 7.99,
      category: 'Appetizer',
      allergens: [],
      modifiers: ['Cajun Seasoning'],
      note: '',
    },
    {
      name: 'Spaghetti',
      picture: 'images/spaghetti.jpg',
      description: 'Classic spaghetti noodles served with marinara sauce and meatballs.',
      price: 13.99,
      category: 'Entree',
      allergens: ['Gluten'],
      modifiers: ['No Sauce', 'No Meatballs'],
      note: '',
    },
    {
      name: 'Tortellini Soup',
      picture: 'images/tortellini-soup.jpg',
      description: 'Hearty soup with cheese-filled tortellini, vegetables, and a savory broth.',
      price: 10.99,
      category: 'Appetizer',
      allergens: ['Dairy', 'Gluten'],
      modifiers: [],
      note: '',
    },
    {
      name: 'Salmon',
      picture: 'images/baked-salmon.jpg',
      description: 'A perfectly seasoned and baked salmon fillet.',
      price: 22.99,
      category: 'Entree',
      allergens: ['Fish'],
      modifiers: [],
      note: '',
    },
    {
      name: 'Glazed Carrots',
      picture: 'images/glazed-carrots.jpg',
      description: 'Tender carrots glazed with a sweet and savory sauce.',
      price: 6.99,
      category: 'Appetizer',
      allergens: [],
      modifiers: [],
      note: '',
    },
    {
      name: 'Iced Tea',
      picture: 'images/iced-tea.jpg',
      description: 'Refreshing iced tea, lightly sweetened.',
      price: 3.49,
      category: 'Drink',
      allergens: [],
      modifiers: ['No Sweetener'],
      note: '',
    },
    {
      name: 'Lemonade',
      picture: 'images/lemonade.jpeg',
      description: 'Classic lemonade made with fresh lemons and a touch of sweetness.',
      price: 3.49,
      category: 'Drink',
      allergens: [],
      modifiers: ['Strawberry Flavor', 'Blueberry Flavor'],
      note: '',
    },
    {
      name: 'Sparkling Cider',
      picture: 'images/martinellis-sparkling-cider.jpg',
      description: 'Martinellis carbonated apple cider.',
      price: 4.99,
      category: 'Drink',
      allergens: [],
      modifiers: [],
      note: '',
    },
    {
      name: 'Minestrone Soup',
      picture: 'images/minestrone-soup.jpg',
      description:
        'A hearty Italian soup filled with vegetables, beans, and pasta in a savory broth.',
      price: 9.99,
      category: 'Appetizer',
      allergens: ['Gluten'],
      modifiers: [],
      note: '',
    },
    {
      name: 'Orange Juice',
      picture: 'images/orange-juice.png',
      description: 'Freshly squeezed orange juice with a bright and tangy flavor.',
      price: 4.49,
      category: 'Drink',
      allergens: [],
      modifiers: ['No Pulp'],
      note: '',
    },
    {
      name: 'Watermelon Mojito',
      picture: 'images/watermelon-mojito.jpg',
      description: 'A refreshing cocktail made with fresh watermelon, mint, lime juice, and rum.',
      price: 9.99,
      category: 'Drink',
      allergens: [],
      modifiers: ['No Alcohol'],
      note: 'This is an alcoholic beverage.',
    },
  ];

  getFullMenu(): MenuItem[] {
    return this.menu;
  }
}
